sudo: required
services: 
  - docker

before_install:
  - docker build -t solb/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true solb/react-test npm test
after_success:
  - docker build -t solb/multi-client -f ./client
  - docker build -t solb/multi-nginx -f ./nginx  
  - docker build -t solb/multi-server -f ./server 
  - docker build -t solb/multi-worker -f ./worker 

  #Log in Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push the to docker hub
  - docker push solb/muti-client
  - docker push solb/muti-nginx
  - docker push solb/muti-server
  - docker push solb/muti-worker