sudo: required
services: 
  - docker

before_install:
  - docker build -t solb/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true solb/react-test npm test
after_success:
  - docker build -t solb/multi-client ./client
  - docker build -t solb/multi-nginx ./nginx  
  - docker build -t solb/multi-server ./server 
  - docker build -t solb/multi-worker ./worker 

  #Log in Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push the to docker hub
  - docker push solb/multi-client
  - docker push solb/multi-nginx
  - docker push solb/multi-server
  - docker push solb/multi-worker